{{-- Generated by Copilot for temporary use. Will edit later --}}
@extends('layouts.app')

@section('content')
<div class="container mt-4">
    <h3>Pending Payment Orders</h3>
    
    <table class="table table-bordered" id="orderTable">
        <thead>
            <tr>
                <th>Order Number</th>
                <th>Buyer</th>
                <th>Total (Rp)</th>
                <th>Created</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <!-- Filled by JavaScript -->
        </tbody>
    </table>

    <a class="btn btn-secondary mt-3" href="{{ url('/admin') }}">Back to Dashboard</a>
</div>
@endsection

@section('scripts')
<script>
// Load orders on page load
document.addEventListener('DOMContentLoaded', () =>{
    loadOrders();
    checkAuth();
});

// Check if user is authenticated
function checkAuth() {
    const token = localStorage.getItem('admin_token');
    const user = JSON.parse(localStorage.getItem('admin_user') || '{}');
    
    if (!token || user.role !== 'bumdes') {
        window.location.href = '/admin/login';
        return false;
    }
    return true;
}

// Get token for API requests
function getAuthHeaders() {
    return {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + localStorage.getItem('admin_token')
    };
}

// Load orders with token
function loadOrders() {
    fetch('/api/admin/orders?status=pending_payment', {
        headers: getAuthHeaders()
    })
    .then(res => {
        if (res.status === 401 || res.status === 403) {
            logout();
            return;
        }
        return res.json();
    })
    .then(orders => {
        if (!orders) return;
        
        let html = orders.map(order => `
            <tr>
                <td>${order.order_number}</td>
                <td>${order.buyer.name}</td>
                <td>${order.total.toLocaleString()}</td>
                <td>${new Date(order.created_at).toLocaleDateString()}</td>
                <td>
                    <button class="btn btn-sm btn-success" 
                            onclick="confirmPayment(${order.id})">
                        Confirm Payment
                    </button>
                    <button class="btn btn-sm btn-danger ms-1" 
                            onclick="rejectPayment(${order.id})">
                        Reject
                    </button>
                </td>
            </tr>
        `).join('');
        
        document.querySelector('#orderTable tbody').innerHTML = html || 
            '<tr><td colspan="5" class="text-center">No pending orders</td></tr>';
    })
    .catch(() => logout());
}

// Confirm payment with token
function confirmPayment(orderId) {
    if (!confirm('Confirm payment for this order?')) return;
    
    fetch(`/api/admin/orders/${orderId}/confirm-payment`, {
        method: 'POST',
        headers: getAuthHeaders()
    })
    .then(res => {
        if (res.status === 401 || res.status === 403) {
            logout();
            return;
        }
        return res.json();
    })
    .then(data => {
        if (data) {
            alert(data.message);
            loadOrders();
        }
    });
}

// Reject payment with token
function rejectPayment(orderId) {
    if (!confirm('Are you sure you want to reject this payment?')) return;
    
    fetch(`/api/admin/orders/${orderId}/reject-payment`, {
        method: 'POST',
        headers: getAuthHeaders()
    })
    .then(res => {
        if (res.status === 401 || res.status === 403) {
            logout();
            return;
        }
        return res.json();
    })
    .then(data => {
        if (data) {
            alert(data.message);
            loadOrders();
        }
    });
}
</script>
@endsection