{{-- Generated by Copilot for temporary use. Will edit later --}}
@extends('layouts.app')

@section('content')
<div class="container mt-4">
    <h3>Pending Payment Orders</h3>
    
    <table class="table table-bordered" id="orderTable">
        <thead>
            <tr>
                <th>Order Number</th>
                <th>Buyer</th>
                <th>Total (Rp)</th>
                <th>Created</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <!-- Filled by JavaScript -->
        </tbody>
    </table>

    <a class="btn btn-secondary mt-3" href="{{ url('/admin') }}">Back to Dashboard</a>
</div>
@endsection

@section('scripts')
<script>
// Load orders on page load
document.addEventListener('DOMContentLoaded', () => loadOrders());

// Fetch and display orders
function loadOrders() {
    fetch('/api/admin/orders?status=pending_payment')
        .then(res => res.json())
        .then(orders => {
            let html = orders.map(order => `
                <tr>
                    <td>${order.order_number}</td>
                    <td>${order.buyer.name}</td>
                    <td>${order.total.toLocaleString()}</td>
                    <td>${new Date(order.created_at).toLocaleDateString()}</td>
                    <td>
                        <button class="btn btn-sm btn-success" 
                                onclick="confirmPayment(${order.id})">
                            Confirm Payment
                        </button>
                    </td>
                </tr>
            `).join('');
            
            document.querySelector('#orderTable tbody').innerHTML = html || 
                '<tr><td colspan="5" class="text-center">No pending orders</td></tr>';
        });
}

// Confirm payment
function confirmPayment(orderId) {
    if (!confirm('Confirm payment for this order?')) return;
    
    fetch(`/api/admin/orders/${orderId}/confirm-payment`, { method: 'POST' })
        .then(res => res.json())
        .then(data => {
            alert(data.message);
            loadOrders(); // Refresh table
        });
}
</script>
@endsection